version: '2'

# persist changes in your home directory
volumes:
  home:

services:
  botanbot_lcas:
    build: .
    restart: unless-stopped
    image: lcas.lincoln.ac.uk/lcas/botanbot_lcas:docker
    environment:
      RESOLUTION: 1280x720
    volumes:
      - ../.:/volume/host
    ports:
      - "6080:80"
      - "6081:8888"
