name: foxy

on: [push, pull_request]

jobs:
    job1:
        name: Build
        runs-on: ubuntu-20.04
        steps:
            - name: Install ROS2 Foxy 
              run: |
                  # Ref: https://index.ros.org/doc/ros2/Installation/Foxy/Linux-Install-Debians/
                  sudo locale-gen en_US en_US.UTF-8
                  sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
                  export LANG=en_US.UTF-8
                  sudo apt update && sudo apt install curl gnupg2 lsb-release
                  curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
                  sudo sh -c 'echo "deb [arch=amd64,arm64] http://packages.ros.org/ros2/ubuntu `lsb_release -cs` main" > /etc/apt/sources.list.d/ros2-latest.list'
                  sudo apt update
                  sudo apt install ros-foxy-desktop
                  source /opt/ros/foxy/setup.bash
            - name: Create Workspace
              run: |
                  mkdir -p ~/ros2_ws/src
            - name: Install Dependencies and Build Botanbot Packges
              run: |
                  source /opt/ros/foxy/setup.bash
                  sudo apt install python3-colcon-common-extensions
                  sudo apt install -y python3-rosdep2
                  sudo apt-get install git
                  rosdep update
                  cd ~/ros2_ws/src
                  git clone --recursive https://github.com/NMBURobotics/botanbot_sim.git
                  cd ~/ros2_ws
                  rosdep install -y -r -q --from-paths src --ignore-src --rosdistro foxy   
                  colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release --parallel-workers 4
